/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 15 06:02:49 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.ATM;
import tutorial.ATMCard;
import tutorial.Bank;
import tutorial.Person;
import tutorial.SavingsAccount;
import tutorial.SavingsAccount2;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ATM_ESTest extends ATM_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Bank bank0 = new Bank();
      Person person0 = new Person("5", ";=)r0+D/r4`{0 c");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(person0);
      savingsAccount2_0.balance = 0;
      savingsAccount2_0.balance = 151;
      bank0.addAccount(savingsAccount2_0);
      Person person1 = new Person("tutorial.ATM", "z'EF0W/#qG{K==");
      SavingsAccount savingsAccount0 = new SavingsAccount(person1);
      bank0.hasBankAccount(savingsAccount0);
      ATM aTM0 = new ATM(bank0);
      aTM0.ejectCard();
      aTM0.deposit(1);
      int[] intArray0 = new int[5];
      intArray0[1] = 1;
      intArray0[2] = 1;
      intArray0[4] = 1;
      ATMCard aTMCard0 = new ATMCard(person0, savingsAccount2_0, intArray0);
      int[] intArray1 = new int[1];
      intArray1[0] = 151;
      aTMCard0.setPin(intArray1);
      aTM0.insertCard(aTMCard0);
      int[] intArray2 = new int[1];
      intArray2[0] = 1;
      aTM0.enterPin(intArray2);
      aTM0.ejectCard();
  }
}
