/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 15 05:50:33 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Company;
import tutorial.CurrentAccount;
import tutorial.Owner;
import tutorial.Person;
import tutorial.SavingsAccount;
import tutorial.SavingsAccount2;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BankAccount_ESTest extends BankAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Person person0 = new Person("F15*58fFt4PVrb", "'dud}4vcn");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, (-1));
      currentAccount0.withdraw((-3297));
      assertEquals(3297, currentAccount0.getBalance());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Company company0 = new Company("");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(company0);
      savingsAccount2_0.withdraw(2080);
      assertEquals(0, savingsAccount2_0.getBalance());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      savingsAccount0.getOwner();
      assertEquals(0, savingsAccount0.getBalance());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Company company0 = new Company("6_\"O^VazUcg)H");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(company0);
      savingsAccount2_0.balance = 402;
      int int0 = savingsAccount2_0.getBalance();
      assertEquals(402, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Company company0 = new Company("");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(company0);
      savingsAccount2_0.deposit((-119));
      int int0 = savingsAccount2_0.getBalance();
      assertEquals((-119), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Person person0 = new Person("I-K", "I-K");
      CurrentAccount currentAccount0 = new CurrentAccount(person0, 1084);
      int int0 = currentAccount0.getBalance();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Person person0 = new Person("I-K", "I-K");
      SavingsAccount savingsAccount0 = new SavingsAccount(person0);
      Owner owner0 = savingsAccount0.getOwner();
      assertNotNull(owner0);
      assertEquals(0, savingsAccount0.getBalance());
  }
}
