/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 15 06:30:40 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.GFG2;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GFG2_ESTest extends GFG2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = GFG2.calculate_ways(1, (-719));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = GFG2.binomial_coefficient(1, 57);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = GFG2.binomial_coefficient(0, 0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = GFG2.calculate_ways(0, 0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = GFG2.binomial_coefficient(1712701, 995);
      assertEquals((-605608), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      GFG2.calculate_ways(1471875, 1471875);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = GFG2.calculate_ways((-1603794), 1340);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int int0 = GFG2.binomial_coefficient(1340, 1340);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      int int0 = GFG2.calculate_ways(1340, 1340);
      assertEquals((-1603794), int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      GFG2 gFG2_0 = new GFG2();
  }
}
