/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 15 06:31:54 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.GFG3;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GFG3_ESTest extends GFG3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = GFG3.evenbitsetnumber(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = GFG3.evenbitsetnumber(1318);
      assertEquals(1966, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = GFG3.evenbitsetnumber((-516));
      assertEquals((-516), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GFG3 gFG3_0 = new GFG3();
  }
}
