/*
 * This file was automatically generated by EvoSuite
 * Mon Dec 10 00:22:19 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.MST;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MST_ESTest extends MST_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MST mST0 = new MST();
      int[][] intArray0 = new int[5][8];
      int[] intArray1 = new int[9];
      intArray1[1] = Integer.MAX_VALUE;
      intArray0[0] = intArray1;
      // Undeclared exception!
      try { 
        mST0.primMST(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("tutorial.MST", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MST mST0 = new MST();
      int[][] intArray0 = new int[5][8];
      int[] intArray1 = new int[9];
      intArray1[0] = 1685;
      intArray0[0] = intArray1;
      // Undeclared exception!
      try { 
        mST0.primMST(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("tutorial.MST", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MST mST0 = new MST();
      int[][] intArray0 = new int[5][8];
      int[] intArray1 = new int[9];
      intArray1[2] = 1005;
      intArray1[3] = (-3483);
      intArray1[4] = 1628;
      intArray0[0] = intArray1;
      mST0.primMST(intArray0);
      assertEquals(5, intArray0.length);
  }
}
