/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 15 05:51:57 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Person;
import tutorial.SavingsAccount2;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SavingsAccount2_ESTest extends SavingsAccount2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Person person0 = new Person("", "");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(person0);
      boolean boolean0 = savingsAccount2_0.withdraw((-1089));
      assertEquals(1089, savingsAccount2_0.getBalance());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Person person0 = new Person("", "");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(person0);
      savingsAccount2_0.deposit(1543);
      assertEquals(1543, savingsAccount2_0.getBalance());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Person person0 = new Person("", "");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(person0);
      boolean boolean0 = savingsAccount2_0.withdraw(1543);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Person person0 = new Person("", "");
      SavingsAccount2 savingsAccount2_0 = new SavingsAccount2(person0);
      boolean boolean0 = savingsAccount2_0.withdraw(0);
      assertEquals(0, savingsAccount2_0.getBalance());
      assertTrue(boolean0);
  }
}
