/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 15 05:52:30 GMT 2018
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.Owner;
import tutorial.SavingsAccount;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SavingsAccount_ESTest extends SavingsAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      savingsAccount0.balance = (-2002);
      boolean boolean0 = savingsAccount0.withdraw((-2002));
      assertEquals(0, savingsAccount0.getBalance());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      boolean boolean0 = savingsAccount0.withdraw(3646);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      boolean boolean0 = savingsAccount0.withdraw((-1020));
      assertEquals(1020, savingsAccount0.getBalance());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SavingsAccount savingsAccount0 = new SavingsAccount((Owner) null);
      savingsAccount0.deposit((-1155));
      assertEquals((-1155), savingsAccount0.getBalance());
  }
}
